[tools]
claude = "latest"
fzf = "latest"
navi = "latest"
neovim = "latest"
node = "latest"
"npm:skills" = "latest"
starship = "latest"
topgrade = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"
